spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  s3:
    s3-bucket-access-key: ${S3_BUCKET_ACCESS_KEY:}
    s3-bucket-secret-key: ${S3_BUCKET_SECRET_KEY:}
    s3-bucket-region: ${S3_BUCKET_REGION:us-east-1}
    s3-bucket-name: ${S3_BUCKET_NAME:}

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}
        same-site: ${SESSION_COOKIE_SAME_SITE:none}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"
  level:
    root: INFO
    com.talentFlow: INFO
    org.springframework.boot.web: INFO

app:
  security:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
    password-reset-frontend-url: ${PASSWORD_RESET_FRONTEND_URL}
    login-url: ${LOGIN_URL}

  seed:
    admin:
      enabled: ${ADMIN_SEED_ENABLED:false}
      email: ${ADMIN_SEED_EMAIL}
      password: ${ADMIN_SEED_PASSWORD}
      first-name: ${ADMIN_SEED_FIRST_NAME}
      last-name: ${ADMIN_SEED_LAST_NAME}
      update-password: ${ADMIN_SEED_UPDATE_PASSWORD:false}
  mail:
    from: ${EMAIL_FROM}


  jpa:
      defer-datasource-initialization: true
  main:
      lazy-initialization: true
