spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: ${EMAIL_HOST:smtp.resend.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:resend}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: ${EMAIL_CONNECTION_TIMEOUT:5000}
          timeout: ${EMAIL_TIMEOUT:5000}
          writetimeout: ${EMAIL_WRITE_TIMEOUT:5000}
          starttls:
            enable: true
          ssl:
            enable: ${EMAIL_SECURE:false}
  s3:
    s3-bucket-access-key: ${S3_BUCKET_ACCESS_KEY:}
    s3-bucket-secret-key: ${S3_BUCKET_SECRET_KEY:}
    s3-bucket-region: ${S3_BUCKET_REGION:us-east-1}
    s3-bucket-name: ${S3_BUCKET_NAME:}

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}
        same-site: ${SESSION_COOKIE_SAME_SITE:none}

logging:
  level:
    org.springframework.boot.web: DEBUG

app:
  security:
    verification-token-frontend-url: ${VERIFICATION_TOKEN_FRONTEND_URL}
    password-reset-frontend-url: ${PASSWORD_RESET_FRONTEND_URL}
    login-url: ${LOGIN_URL}

  seed:
    admin:
      enabled: ${ADMIN_SEED_ENABLED:false}
      email: ${ADMIN_SEED_EMAIL}
      password: ${ADMIN_SEED_PASSWORD}
      first-name: ${ADMIN_SEED_FIRST_NAME}
      last-name: ${ADMIN_SEED_LAST_NAME}
      update-password: ${ADMIN_SEED_UPDATE_PASSWORD:false}
  mail:
    from: ${EMAIL_FROM}

  jpa:
      defer-datasource-initialization: true
  main:
      lazy-initialization: true
